import os
import re
import base64
import traceback
import sys

# -------------------------
# Hard fail on error
# -------------------------
def excepthook(exc_type, exc, tb):
    print("\n?? ERROR CAUGHT ??")
    traceback.print_exception(exc_type, exc, tb)
    sys.exit(1)

sys.excepthook = excepthook

# -------------------------
# Configuration
# -------------------------
REPO_ROOT = r"C:\Users\jesse\Desktop\anattagen"
TMP_DIR = os.path.join(REPO_ROOT, "tmp")
OUTPUT_FILE = os.path.join(TMP_DIR, "all_code.py")

EXCLUDED_FILES = {
    os.path.abspath(os.path.join(REPO_ROOT, "Launcher.py")),
}

ASSET_EXTENSIONS = (".ico", ".set", ".ttf", ".png", ".html")

os.makedirs(TMP_DIR, exist_ok=True)

# -------------------------
# Asset embedding
# -------------------------
def collect_assets(directory):
    assets = {}
    for root, _, files in os.walk(directory):
        for file in files:
            if file.lower().endswith(ASSET_EXTENSIONS):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, directory)
                assets[rel_path.replace("\\", "/")] = full_path
    return assets

ASSETS = collect_assets(REPO_ROOT)

def write_assets_runtime():
    lines = [
        "def _write_assets():",
        "    import os, base64",
        "    _assets = {"
    ]

    for rel, full in ASSETS.items():
        with open(full, "rb") as f:
            encoded = base64.b64encode(f.read()).decode("utf-8")
        lines.append(f'        "{rel}": "{encoded}",')

    lines += [
        "    }",
        "    for rel_path, data in _assets.items():",
        "        out_path = os.path.join(os.getcwd(), rel_path)",
        "        os.makedirs(os.path.dirname(out_path), exist_ok=True)",
        "        with open(out_path, 'wb') as f:",
        "            f.write(base64.b64decode(data))",
        "",
        "_write_assets()",
        ""
    ]

    return "\n".join(lines)

# -------------------------
# Python collection
# -------------------------
def collect_python_files(directory):
    py_files = []
    this_script = os.path.abspath(__file__)

    for file in os.listdir(directory):
        if not file.endswith(".py"):
            continue

        full_path = os.path.abspath(os.path.join(directory, file))

        if full_path == this_script:
            continue
        if full_path in EXCLUDED_FILES:
            continue

        py_files.append(full_path)

    return py_files

def strip_imports(code):
    """
    Remove local imports since everything is inlined.
    """
    cleaned = []
    for line in code.splitlines():
        if re.match(r'^\s*(import|from)\s+[a-zA-Z_]', line):
            continue
        cleaned.append(line)
    return "\n".join(cleaned)

# -------------------------
# Build standalone file
# -------------------------
py_files = collect_python_files(REPO_ROOT)
py_files.sort()

if not py_files:
    raise RuntimeError("No Python files found to concatenate")

print("Including Python files:")
for f in py_files:
    print("  -", os.path.basename(f))

full_code = [
    "#!/usr/bin/env python",
    "# =========================================",
    "# AUTOGENERATED STANDALONE FILE",
    "# =========================================",
    "",
    write_assets_runtime(),
]

for py_file in py_files:
    with open(py_file, "r", encoding="utf-8") as f:
        code = f.read()

    code = strip_imports(code)

    if code.strip():
        full_code.append(f"\n# -------- {os.path.basename(py_file)} --------\n")
        full_code.append(code)

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(full_code))

print(f"\n✔ Standalone file written to: {OUTPUT_FILE}")
print(f"✔ Assets embedded: {len(ASSETS)} files")
