import os
from enum import Enum

# --- Core Paths ---
# The absolute path to the root of the application.
APP_ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
# The directory where assets like icons and .set files are stored.
ASSETS_DIR = os.path.join(APP_ROOT_DIR, "assets")

# --- Asset File Paths ---
APP_ICON = os.path.join(ASSETS_DIR, "anattagen.ico")
REPOS_SET = os.path.join(ASSETS_DIR, "repos.set")
RELEASE_GROUPS_SET = os.path.join(ASSETS_DIR, "release_groups.set")
FOLDER_EXCLUDE_SET = os.path.join(ASSETS_DIR, "folder_exclude.set")
EXCLUDE_EXE_SET = os.path.join(ASSETS_DIR, "exclude_exe.set")
DEMOTED_SET = os.path.join(ASSETS_DIR, "demoted.set")
FOLDER_DEMOTED_SET = os.path.join(ASSETS_DIR, "folder_demoted.set")

# --- Data/Cache File Paths ---
# These files are generated by the application and stored in the root directory.
STEAM_JSON_FILE = os.path.join(APP_ROOT_DIR, "steam.json")
STEAM_FILTERED_TXT = "steam_filtered.txt"
NORMALIZED_INDEX_CACHE = "normalized_steam_games.cache"

# --- Editor Column Indices ---
class EditorCols(Enum):
    INCLUDE = 0
    NAME = 1
    DIRECTORY = 2
    STEAMID = 3
    NAME_OVERRIDE = 4
    OPTIONS = 5
    ARGUMENTS = 6
    RUN_AS_ADMIN = 7
    CM_ENABLED = 8
    CM_PATH = 9
    CM_RUN_WAIT = 10
    BW_ENABLED = 11
    BW_PATH = 12
    BW_RUN_WAIT = 13
    MM_ENABLED = 14
    MM_PATH = 15
    MM_RUN_WAIT = 16
    HIDE_TASKBAR = 17
    MM_GAME_PROFILE = 18
    MM_DESKTOP_PROFILE = 19
    PLAYER1_PROFILE = 20
    PLAYER2_PROFILE = 21
    MEDIACENTER_PROFILE = 22
    JA_ENABLED = 23
    JA_PATH = 24
    JA_RUN_WAIT = 25
    JB_ENABLED = 26
    JB_PATH = 27
    JB_RUN_WAIT = 28
    PRE1_ENABLED = 29
    PRE1_PATH = 30
    PRE1_RUN_WAIT = 31
    POST1_ENABLED = 32
    POST1_PATH = 33
    POST1_RUN_WAIT = 34
    PRE2_ENABLED = 35
    PRE2_PATH = 36
    PRE2_RUN_WAIT = 37
    POST2_ENABLED = 38
    POST2_PATH = 39
    POST2_RUN_WAIT = 40
    PRE3_ENABLED = 41
    PRE3_PATH = 42
    PRE3_RUN_WAIT = 43
    POST3_ENABLED = 44
    POST3_PATH = 45
    POST3_RUN_WAIT = 46
