import os
from enum import Enum

# --- Core Paths ---
# The absolute path to the root of the application.
APP_ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
# The directory where assets like icons and .set files are stored.
ASSETS_DIR = os.path.join(APP_ROOT_DIR, "assets")

# --- Asset File Paths ---
APP_ICON = os.path.join(ASSETS_DIR, "anattagen.ico")
REPOS_SET = os.path.join(ASSETS_DIR, "repos.set")
LAUNCHER_EXECUTABLE = os.path.join(APP_ROOT_DIR, "bin", "Launcher.exe")
RELEASE_GROUPS_SET = os.path.join(ASSETS_DIR, "release_groups.set")
FOLDER_EXCLUDE_SET = os.path.join(ASSETS_DIR, "folder_exclude.set")
EXCLUDE_EXE_SET = os.path.join(ASSETS_DIR, "exclude_exe.set")
DEMOTED_SET = os.path.join(ASSETS_DIR, "demoted.set")
FOLDER_DEMOTED_SET = os.path.join(ASSETS_DIR, "folder_demoted.set")
KILLPROCS_SET = os.path.join(ASSETS_DIR, "killprocs.set")
OPTIONS_ARGUMENTS_SET = os.path.join(ASSETS_DIR, "options_arguments.set")

# --- Data/Cache File Paths ---
# These files are generated by the application and stored in the root directory.
STEAM_JSON_FILE = os.path.join(APP_ROOT_DIR, "steam.json")
STEAM_FILTERED_TXT = "steam_filtered.txt"
NORMALIZED_INDEX_CACHE = "normalized_steam_games.cache"

# --- Editor Column Indices ---
class EditorCols(Enum):
    INCLUDE = 0
    NAME = 1
    DIRECTORY = 2
    STEAMID = 3
    NAME_OVERRIDE = 4
    OPTIONS = 5
    ARGUMENTS = 6
    RUN_AS_ADMIN = 7
    CM_PATH = 8
    CM_RUN_WAIT = 9
    BW_PATH = 10
    BW_RUN_WAIT = 11
    WIN_EXIT = 12
    MM_PATH = 13
    MM_RUN_WAIT = 14
    HIDE_TASKBAR = 15
    MM_GAME_PROFILE = 16
    MM_DESKTOP_PROFILE = 17
    PLAYER1_PROFILE = 18
    PLAYER2_PROFILE = 19
    MEDIACENTER_PROFILE = 20
    JA_PATH = 21
    JA_RUN_WAIT = 22
    JB_PATH = 23
    JB_RUN_WAIT = 24
    PRE1_PATH = 25
    PRE1_RUN_WAIT = 26
    POST1_PATH = 27
    POST1_RUN_WAIT = 28
    PRE2_PATH = 29
    PRE2_RUN_WAIT = 30
    POST2_PATH = 31
    POST2_RUN_WAIT = 32
    PRE3_PATH = 33
    PRE3_RUN_WAIT = 34
    POST3_PATH = 35
    POST3_RUN_WAIT = 36
    KILL_LIST = 37
    LAUNCHER_EXE = 38
